### ISSUE TITLE
Allow custom SSH keys

### ISSUE THREAD

**Issue by d4ncer** [marianogappa/sql#11]
Great project, thanks for creating / maintaining it!

I'd like to configure a custom SSH key to use either across the board or on a server-by-server basis, with some fallback. 

I don't have a possible solution yet; will append to this as and when I do.

**Comment by marianogappa** [comment]
I can think of 3 options for configuring this:

1. command line argument

1. environment variable

1. within .databases.json

I dislike option 1 because it would become very annoying really quickly to type it out every single time. Option 2 works well if one wants to override the default SSH key every time and always with the same key. Option 3 would be the most flexible in that one could even specify different keys for different databases. As long as the field is optional, it doesn't complicate the model nor the code too much.

**Comment by marianogappa** [comment]
How about a mix of 2. and 3., with 2. overriding 3?

**Comment by d4ncer** [comment]
I agree, except I think 3 should override 2. I see the env variable acting as a catchall key, with the option of overriding it with a specific key for a given server/db.

**Comment by d4ncer** [comment]
Closing this out; you can make this work with an existing SSH config by modifying the `appServer` key for a given host to match the hostname in your SSH config.
